services:
    # Twig extension
    app.blog.twig.extension:
        class: Puzzle\App\BlogBundle\Twig\PuzzleAppBlogExtension
        arguments: [ '@request_stack', '@event_dispatcher', '@puzzle_connect.api_client' ]
        tags:
          - { name: twig.extension }